In [50]:
import pandas as pd 
import numpy as np
from google.colab import drive
from datetime import datetime
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [51]:
df = pd.read_pickle('/content/drive/MyDrive/Grupo Facens DataScience/TCC/Grupo 1/Codes/Arquivos/INFLUD21-27-09-2021-NoMissing.pkl')

In [53]:
df.head()

DT_NOTIFIC  DT_SIN_PRI CS_SEXO  ...  VACINA_COV  DOSE_1_COV  DOSE_2_COV
12  13/01/2021  03/01/2021       F  ...         2.0         NaN         NaN
32  12/01/2021  07/01/2021       M  ...         2.0         NaN         NaN
37  14/01/2021  04/01/2021       M  ...         2.0         NaN         NaN
43  11/01/2021  04/01/2021       M  ...         9.0         NaN         NaN
66  07/01/2021  03/01/2021       M  ...         2.0         NaN         NaN

[5 rows x 42 columns]

In [54]:
df.dtypes

DT_NOTIFIC     object
DT_SIN_PRI     object
CS_SEXO        object
CS_GESTANT      int64
CS_RACA         int64
NOSOCOMIAL    float64
FEBRE         float64
TOSSE         float64
GARGANTA      float64
DISPNEIA      float64
DESC_RESP     float64
SATURACAO     float64
DIARREIA      float64
VOMITO        float64
PUERPERA      float64
FATOR_RISC      int64
CARDIOPATI    float64
HEMATOLOGI    float64
SIND_DOWN     float64
HEPATICA      float64
ASMA          float64
DIABETES      float64
NEUROLOGIC    float64
PNEUMOPATI    float64
IMUNODEPRE    float64
RENAL         float64
OBESIDADE     float64
VACINA        float64
ANTIVIRAL     float64
DT_ENTUTI      object
DT_SAIDUTI     object
SUPORT_VEN    float64
CLASSI_FIN    float64
CLASSI_OUT     object
EVOLUCAO      float64
DOR_ABD       float64
FADIGA        float64
PERD_OLFT     float64
PERD_PALA     float64
VACINA_COV    float64
DOSE_1_COV     object
DOSE_2_COV     object
dtype: object

In [55]:
ColumnsObject =  ['CS_GESTANT', #(Checar se existe masculino com gestante Sim)
         'PUERPERA',   #Habilitado se selecionado no campo 8- Sexo Feminino.
         'CARDIOPATI',
         'HEMATOLOGI',
         'SIND_DOWN',
         'HEPATICA',
         'ASMA',
         'DIABETES',
         'NEUROLOGIC',
         'PNEUMOPATI',
         'IMUNODEPRE',
         'RENAL',
         'OBESIDADE',   
         'DOSE_1_COV', #Mudar para 0 e 1 para definir se teve ou nao
         'DOSE_2_COV', #Mudar para 0 e 1 para definir se teve ou nao
        'CS_RACA',
        'NOSOCOMIAL',
        'FATOR_RISC',
        'CARDIOPATI',
        'HEMATOLOGI',
        'SIND_DOWN',
        'HEPATICA',
        'ASMA',
        'DIABETES',
        'NEUROLOGIC',
        'PNEUMOPATI',
        'IMUNODEPRE',
        'RENAL',
        'OBESIDADE',
        'FEBRE',
        'TOSSE',
        'GARGANTA',
        'DISPNEIA',
        'DESC_RESP',
        'SATURACAO',
        'DIARREIA',
        'VOMITO',
        'DOR_ABD',
        'FADIGA',
        'PERD_OLFT',
        'PERD_PALA', 
        'VACINA',
        'ANTIVIRAL',
        'SUPORT_VEN',
        'VACINA_COV']



In [56]:
for columns in ColumnsObject:
    df[columns]=df[columns].astype('object')

In [57]:
df.dtypes

DT_NOTIFIC     object
DT_SIN_PRI     object
CS_SEXO        object
CS_GESTANT     object
CS_RACA        object
NOSOCOMIAL     object
FEBRE          object
TOSSE          object
GARGANTA       object
DISPNEIA       object
DESC_RESP      object
SATURACAO      object
DIARREIA       object
VOMITO         object
PUERPERA       object
FATOR_RISC     object
CARDIOPATI     object
HEMATOLOGI     object
SIND_DOWN      object
HEPATICA       object
ASMA           object
DIABETES       object
NEUROLOGIC     object
PNEUMOPATI     object
IMUNODEPRE     object
RENAL          object
OBESIDADE      object
VACINA         object
ANTIVIRAL      object
DT_ENTUTI      object
DT_SAIDUTI     object
SUPORT_VEN     object
CLASSI_FIN    float64
CLASSI_OUT     object
EVOLUCAO      float64
DOR_ABD        object
FADIGA         object
PERD_OLFT      object
PERD_PALA      object
VACINA_COV     object
DOSE_1_COV     object
DOSE_2_COV     object
dtype: object

# 'PUERPERA'

In [58]:
#remove todas as linhas onde Puerpera possui valores vazios
df = df[df['PUERPERA'].isnull()!=True]
df.shape

(282554, 42)

In [59]:
#Valores = 1, algum se refere a homem? / Valores = 1, Algum aparece como gestante? 
print("Valores de Puerpera", df['PUERPERA'].unique())
print("Valores de Puerpera para pacientes do sexo Masculino",df.loc[df['CS_SEXO']=='M','PUERPERA'].unique())
print("Valores de Puerpera para pacientes gestante",df.loc[df['CS_SEXO']=='M','CS_GESTANT'].unique())

Valores de Puerpera [2.0 9.0 1.0]
Valores de Puerpera para pacientes do sexo Masculino [2.0 9.0]
Valores de Puerpera para pacientes gestante [6 5 0 9]


# 'DT_NOTIFIC' & 'DT_SIN_PRI'

In [60]:
#Transformar colunas'DT_NOTIFIC','DT_SIN_PRI'  para formato datetime 
df['DT_NOTIFIC'] = pd.to_datetime(df['DT_NOTIFIC'])
df['DT_SIN_PRI'] = pd.to_datetime(df['DT_SIN_PRI'])

#Não utilizar pois o dado não passa confiança devido a existir datas de notificação futura, cerca de 110k de registros

# 'CS_GESTANT'

In [61]:
## 'CS_GESTANT' Filtrar as linhas com valor 0 / 
print("Numero de linhas em 'CS_GESTANT' com valor igual a 0: ",df[df['CS_GESTANT']==0].shape[0])
df = df[df['CS_GESTANT']!=0] 

#/ Manter os valores 1,2,3,4 e Transformar para 1(sim)
df.loc[df['CS_GESTANT'].isin([1,2,3,4]),'CS_GESTANT'] = 1

#Valores 5 e 6 transformar para 0 
df.loc[df['CS_GESTANT'].isin([5,6]),'CS_GESTANT']=2

print(df['CS_GESTANT'].unique())

Numero de linhas em 'CS_GESTANT' com valor igual a 0:  22
[2 9 1]


/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)


# 'DOSE_1_COV', 'DOSE_2_COV'

In [62]:
#Se tiver valor transformar para 1 
df['DOSE_1_COV'].isnull().value_counts()

True     211103
False     71429
Name: DOSE_1_COV, dtype: int64

In [63]:
df['DOSE_2_COV'].isnull().value_counts()

True     245978
False     36554
Name: DOSE_2_COV, dtype: int64

In [64]:
#Transforma colunas não nulas em 1 
df.loc[df['DOSE_1_COV'].isnull()==False,'DOSE_1_COV']=1
df.loc[df['DOSE_2_COV'].isnull()==False,'DOSE_2_COV']=1
df.loc[df['DOSE_1_COV'].isnull()==True,'DOSE_1_COV']=0
df.loc[df['DOSE_2_COV'].isnull()==True,'DOSE_2_COV']=0

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the d

In [65]:
df['DOSE_1_COV'].unique()

array([0, 1], dtype=object)

In [66]:
df['DOSE_2_COV'].unique()

array([0, 1], dtype=object)

# Mapear os dados: 

In [67]:
for cols in ColumnsObject:
    print(cols)
    print(df[cols].unique())
    print("------------------")
    print('\n')

CS_GESTANT
[2 9 1]
------------------


PUERPERA
[2.0 9.0 1.0]
------------------


CARDIOPATI
[1.0 2.0 9.0]
------------------


HEMATOLOGI
[2.0 9.0 1.0]
------------------


SIND_DOWN
[2.0 9.0 1.0]
------------------


HEPATICA
[2.0 9.0 1.0]
------------------


ASMA
[2.0 1.0 9.0]
------------------


DIABETES
[2.0 1.0 9.0]
------------------


NEUROLOGIC
[2.0 9.0 1.0]
------------------


PNEUMOPATI
[2.0 1.0 9.0]
------------------


IMUNODEPRE
[2.0 1.0 9.0]
------------------


RENAL
[2.0 1.0 9.0]
------------------


OBESIDADE
[1.0 2.0 9.0]
------------------


DOSE_1_COV
[0 1]
------------------


DOSE_2_COV
[0 1]
------------------


CS_RACA
[1 4 3 9 2 5]
------------------


NOSOCOMIAL
[2.0 9.0 1.0]
------------------


FATOR_RISC
[1]
------------------


CARDIOPATI
[1.0 2.0 9.0]
------------------


HEMATOLOGI
[2.0 9.0 1.0]
------------------


SIND_DOWN
[2.0 9.0 1.0]
------------------


HEPATICA
[2.0 9.0 1.0]
------------------


ASMA
[2.0 1.0 9.0]
------------------


DIABE

In [68]:
#Revisar o codigo acima pois deixa NaN em todas as colunas abaixo
mapa = {1:'Sim', 2:'Não', 9:'Ignorado',
        '1':'Sim', '2':'Não', '9':'Ignorado',
       1.0:'Sim', 2.0:'Não', 9.0:'Ignorado',
       }

mapa_suport = {1:'Invasivo', 2:'NãoInvasivo', 3:'Não'} 

cols1 = ['CS_GESTANT', #(Checar se existe masculino com gestante Sim)
         'PUERPERA',   #Habilitado se selecionado no campo 8- Sexo Feminino.
         'CARDIOPATI',
         'HEMATOLOGI',
         'SIND_DOWN',
         'HEPATICA',
         'ASMA',
         'DIABETES',
         'NEUROLOGIC',
         'PNEUMOPATI',
         'IMUNODEPRE',
         'RENAL',
         'OBESIDADE',   
        'NOSOCOMIAL',
        'FATOR_RISC',
         'FEBRE',
        'TOSSE',
        'GARGANTA',
        'DISPNEIA',
        'DESC_RESP',
        'SATURACAO',
        'DIARREIA',
        'VOMITO',
        'DOR_ABD',
        'FADIGA',
        'PERD_OLFT',
        'PERD_PALA', 
        'VACINA',
        'ANTIVIRAL',
        'SUPORT_VEN',
        'VACINA_COV']

In [69]:
for cols in cols1:
  if cols == 'SUPORT_VEN':
    df[cols]=df[cols].map(mapa_suport)
  else:
    df[cols]=df[cols].map(mapa)
    print(cols)
    print(df[cols].unique())
    print("------------------")
    print('\n')

CS_GESTANT
['Não' 'Ignorado' 'Sim']
------------------


PUERPERA
['Não' 'Ignorado' 'Sim']
------------------


CARDIOPATI
['Sim' 'Não' 'Ignorado']
------------------


HEMATOLOGI
['Não' 'Ignorado' 'Sim']
------------------


SIND_DOWN
['Não' 'Ignorado' 'Sim']
------------------


HEPATICA
['Não' 'Ignorado' 'Sim']
------------------


ASMA
['Não' 'Sim' 'Ignorado']
------------------


DIABETES
['Não' 'Sim' 'Ignorado']
------------------


NEUROLOGIC
['Não' 'Ignorado' 'Sim']
------------------


PNEUMOPATI
['Não' 'Sim' 'Ignorado']
------------------


IMUNODEPRE
['Não' 'Sim' 'Ignorado']
------------------


RENAL
['Não' 'Sim' 'Ignorado']
------------------


OBESIDADE
['Sim' 'Não' 'Ignorado']
------------------


NOSOCOMIAL
['Não' 'Ignorado' 'Sim']
------------------


FATOR_RISC
['Sim']
------------------


FEBRE
['Não' 'Sim' 'Ignorado']
------------------


TOSSE
['Sim' 'Não' 'Ignorado']
------------------


GARGANTA
['Sim' 'Não' 'Ignorado']
------------------


DISPNEIA
['Sim' 'Não' 

In [70]:
#Na precisa fazer o mapper aqui, ja foi resolvido na celula acima
cols = [ 'CARDIOPATI',
        'HEMATOLOGI',
        'SIND_DOWN',
        'HEPATICA',
        'ASMA',
        'DIABETES',
        'NEUROLOGIC',
        'PNEUMOPATI',
        'IMUNODEPRE',
        'RENAL',
        'OBESIDADE']
for col in cols:
    #df[col]=df[col].map({1.0:'Sim', 2.0:'Não', 9.0:'Ignorado'})
    print(col)
    print(df[col].unique())
    print("------------------")
    print('\n')



CARDIOPATI
['Sim' 'Não' 'Ignorado']
------------------


HEMATOLOGI
['Não' 'Ignorado' 'Sim']
------------------


SIND_DOWN
['Não' 'Ignorado' 'Sim']
------------------


HEPATICA
['Não' 'Ignorado' 'Sim']
------------------


ASMA
['Não' 'Sim' 'Ignorado']
------------------


DIABETES
['Não' 'Sim' 'Ignorado']
------------------


NEUROLOGIC
['Não' 'Ignorado' 'Sim']
------------------


PNEUMOPATI
['Não' 'Sim' 'Ignorado']
------------------


IMUNODEPRE
['Não' 'Sim' 'Ignorado']
------------------


RENAL
['Não' 'Sim' 'Ignorado']
------------------


OBESIDADE
['Sim' 'Não' 'Ignorado']
------------------




In [71]:
#Realizado a substituicao da numeracao para descricao
df['CS_RACA'] = df['CS_RACA'].map({1:'Branca', 2:'Preta',3:'Amarela',4:'Parda',5:'Indigena',9:'Ignorado'})

In [72]:
df.head()

DT_NOTIFIC DT_SIN_PRI CS_SEXO  ... VACINA_COV DOSE_1_COV DOSE_2_COV
12 2021-01-13 2021-03-01       F  ...        Não          0          0
32 2021-12-01 2021-07-01       M  ...        Não          0          0
37 2021-01-14 2021-04-01       M  ...        Não          0          0
43 2021-11-01 2021-04-01       M  ...   Ignorado          0          0
66 2021-07-01 2021-03-01       M  ...        Não          0          0

[5 rows x 42 columns]

In [73]:
#Removendo pessoas que tomaram a dose 2 e não tomaram a Dose 1 da vacina
df = df[~((df['DOSE_1_COV'] == 0) & (df['DOSE_2_COV'] == 1))]

In [74]:
#Separando as colunas que serão utilizadas no modelo
maincols = ['CS_SEXO', 'CS_GESTANT', 'CS_RACA',
       'NOSOCOMIAL', 'FEBRE', 'TOSSE', 'GARGANTA', 'DISPNEIA', 'DESC_RESP',
       'SATURACAO', 'DIARREIA', 'VOMITO', 'PUERPERA', 'FATOR_RISC',
       'CARDIOPATI', 'HEMATOLOGI', 'SIND_DOWN', 'HEPATICA', 'ASMA', 'DIABETES',
       'NEUROLOGIC', 'PNEUMOPATI', 'IMUNODEPRE', 'RENAL', 'OBESIDADE',
       'VACINA', 'ANTIVIRAL', 'SUPORT_VEN', 'DOR_ABD', 'FADIGA',
       'PERD_OLFT', 'PERD_PALA', 'VACINA_COV', 'DOSE_1_COV', 'DOSE_2_COV']

df = df[maincols]

In [75]:
#Retirando as colunas com inconsistencia  
df = df[~(((df['DOSE_1_COV'] == 1)) & ((df['VACINA_COV'] == 'Não') | (df['VACINA_COV'] == 'Ignorado')))]

In [76]:
#Retirando as colunas com inconsistencia  
df = df[~(((df['DOSE_2_COV'] == 1)) & ((df['VACINA_COV'] == 'Não') | (df['VACINA_COV'] == 'Ignorado')))]

In [77]:
df.shape

(281139, 35)

In [78]:
maincols = ['CS_SEXO', 'CS_GESTANT', 'CS_RACA',
       'NOSOCOMIAL', 'FEBRE', 'TOSSE', 'GARGANTA', 'DISPNEIA', 'DESC_RESP',
       'SATURACAO', 'DIARREIA', 'VOMITO', 'PUERPERA', 'FATOR_RISC',
       'CARDIOPATI', 'HEMATOLOGI', 'SIND_DOWN', 'HEPATICA', 'ASMA', 'DIABETES',
       'NEUROLOGIC', 'PNEUMOPATI', 'IMUNODEPRE', 'RENAL', 'OBESIDADE',
       'VACINA', 'ANTIVIRAL', 'SUPORT_VEN', 'DOR_ABD', 'FADIGA',
       'PERD_OLFT', 'PERD_PALA', 'DOSE_1_COV', 'DOSE_2_COV']

df = df[maincols]

In [79]:
df.head()

CS_SEXO CS_GESTANT CS_RACA  ... PERD_PALA DOSE_1_COV DOSE_2_COV
12       F        Não  Branca  ...       Sim          0          0
32       M        Não  Branca  ...       Não          0          0
37       M        Não   Parda  ...       Não          0          0
43       M        Não  Branca  ...       Não          0          0
66       M        Não   Parda  ...       Não          0          0

[5 rows x 34 columns]

In [81]:
df.to_pickle('INFLUD21-27-09-2021-Tratado.pkl')